version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: ./Docker/var/lib/postgresql/data/pgdata
    volumes:
       - ./Docker/var/lib/postgres:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    restart: on-failure

  php:
    build:
      context: ./Docker/build/php
      dockerfile: Dockerfile
      args:
        uid: 1000
        gid: 1000
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - 9001:9000
    volumes:
      - "./:/var/www/html"
    restart: on-failure
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8089:80
    volumes:
      - ./:/var/www/html
      - ./Docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  redis:
      platform: linux/amd64
      image: redis:latest
      container_name: redis
      environment:
          TZ: Asia/Tehran
      command:
          - --port 6379
          - --requirepass "eRTYUIIUYT5431867DF"
      ports:
          - "6379:6379"
      volumes:
          - ./Docker/volumes/redis:/data
      healthcheck:
          test: [ "CMD", "redis-cli", "ping" ]
          retries: 3
          timeout: 5s

  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: "swagger-ui"
      ports:
          - "8082:8080"
      volumes:
        - ./storage/api-docs:/usr/share/nginx/html/openapi
      environment:
        URLS: "[{url: \"openapi/api-docs.json\", name: \"Api\"}]"
        URLS_PRIMARY_NAME: "App"
        DEEP_LINKING: "true"

