version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: ./Docker/var/lib/postgresql/data/pgdata
    volumes:
       - ./Docker/var/lib/postgres:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    restart: on-failure

  php:
    build:
      context: ./Docker/build/php
      dockerfile: Dockerfile
      args:
        uid: 1000
        gid: 1000
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - 9001:9000
    volumes:
      - "./:/var/www/html"
    restart: on-failure
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8089:80
    volumes:
      - ./htdocs:/var/www/html
      - ./Docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

